### ISSUE TITLE
Performance issues with ODS

### ISSUE THREAD

**Issue by EDM115** [matafokka/ExcelDarkThemeFix#10]
**Describe the bug**
When I try to open an ODS file with multiple sheets, Excel is unresponsive for several minutes  
![image](https://github.com/matafokka/ExcelDarkThemeFix/assets/82015596/5c29c8ff-dbe9-48a2-808f-e692b1802a8d)
![image](https://github.com/matafokka/ExcelDarkThemeFix/assets/82015596/4a3b2061-e4c6-453f-9aa4-2355c0ed4d5e)

Then, I get a VBA error (roughly 5 minutes after) (didn't thought about taking a screenshot, sorry)

And finally, the first sheet is fixed :
![Capture d'écran 2023-10-07 034647](https://github.com/matafokka/ExcelDarkThemeFix/assets/82015596/809933fe-5b96-4751-b659-2f9975e06134)

The second is on a buggy state :
![Capture d'écran 2023-10-07 034652](https://github.com/matafokka/ExcelDarkThemeFix/assets/82015596/76527334-2ee5-4ab0-b019-1999cad8761c)

And the other ones are unfixed :
![Capture d'écran 2023-10-07 034658](https://github.com/matafokka/ExcelDarkThemeFix/assets/82015596/c7175ec6-cde7-4751-b79e-6f338e290075)

Note that opening the same file on LibreOffice just after makes it lag for quite some time too  
The problem isn't from the file, as I opened it multiple times before, it started just after installing Rectify11  
Also I tried to download the OG file just to see if nothing was corrupted, but it changed nothing

**To Reproduce**
Here is the file so you can test it yourself :
[Modele_S3-4.ods](https://github.com/matafokka/ExcelDarkThemeFix/files/12836297/Modele_S3-4.ods)

**Used software:**
1. MS Office version : `2309 (build 16827.20130 Office "Click-To-Run")`
2. Are there any installed Add-Ins or scripts in the workbook? `Apart from this one, no`

**Additional context**
Sometimes the file is opened successfully, and is *mostly* fixed, apart from some colors that are grey instead of black

**Comment by matafokka** [comment]
Hello, thanks for the report!

<s>I think, long loading time even without ExcelDarkThemeFix comes from these huge used ranges.

I suspect that at some point someone changed a cell way down and right from an actual used area.

I didn't get any error, but your Excel might just have ran out of memory. I'll test everything further today. But may I ask you to take a screenshot of that error?

I'll try to make a workaround, but I don't think that there's any except better-looking error message.</s>

Sorry, used range is fine, I looked at the wrong values.

As for the colors, I remember stumbling upon the same bug, and it occurs only on some themes, not all. I think, Excel maps some colors to its own internal table? I'll re-check that. I wasn't able to fix this one and forgot to update README because of frustration, then forgot about it at all. I'm sorry :(

So anyway, I'll try to give more info later today. And thanks again for the report!

**Comment by matafokka** [comment]
Also, please try uninstalling Rectify11 and try to use just [SecureUxTheme](https://github.com/namazso/SecureUxTheme).

I'm not sure if that it'll help, but hey, MS stuff is weird :)

**Comment by matafokka** [comment]
Sad news, my friend, performance problems can't be fixed as well as wrong colors in some cases. I've added a notice in README to warn other users.

Again, thanks for reporting this issue!

**Comment by matafokka** [comment]
Wait, I saved this file as .xlsx, and the problem is gone. Can you try to do the same?

**Comment by EDM115** [comment]
well indeed it solved it  
some formulas are gone due to syntax mismatch between libre office and Excel  
that's why I mentioned that it happens on ODS files

**Comment by matafokka** [comment]
Thank you very much! I'll remove that scary notice from the README then. I'll also read about ODS in Excel, maybe will figure something out :)

**Comment by matafokka** [comment]
Hello again! I found an actual issue. I checked again, and used range actually has been way off, I just looked at the wrong place both times :)

I replaced `Sheet.UsedRange` with `Sheet.Cells.Find()`, and now your file opens pretty fast. Please, download ExcelDarkThemeFix again.

I also checked if ODS is slower than XLSX, and a file with ~100K cells in both formats, and both files take ~3.6 seconds to open on my machine.

However, I added a dialog when user tries to open a file with lots of data.

**Comment by EDM115** [comment]
thank you for still contributing to this !  
I will test this within an hour

**Comment by EDM115** [comment]
god damn it took less than 3 seconds to open !  
you are the master 🙏   
  
maybe create a release ?

**Comment by matafokka** [comment]
Thank you, my friend :)

> maybe create a release ?

I don't think that GitHub releases model works for this project because:

1. I like to push updates and fixes as soon as I can.
2. Sometimes this backfires, and I release a buggy version. I remember headache removing those from GH releases, don't remember the details though.
3. The "source code" is already an artifact.
