### ISSUE TITLE
How i make it work?

### ISSUE THREAD

**Issue by CajuEtex** [matafokka/ExcelDarkThemeFix#2]
I followed all the installation steps and when I try to open any excel file this message appears:
![image](https://user-images.githubusercontent.com/73147420/96527920-b1d65300-1257-11eb-9e19-1e77c9ee7d15.png)
the 'Continue' button is not available, and then if I press 'End', the excel file opens, but with even darker colors than before. I don't know how to fix it, the option "Unblock" in properties doesn't appear for me, i tried all the installation steps and it didn't work.

Before i press 'End':
![image](https://user-images.githubusercontent.com/73147420/96528361-e4348000-1258-11eb-8ec6-c85db45bf7d2.png)

After i press 'End':
![image](https://user-images.githubusercontent.com/73147420/96528329-cebf5600-1258-11eb-9f6a-354e0479eca7.png)

Only if I deactivate the Add-in, it returns to "normal", but still with the dark theme.

**Comment by matafokka** [comment]
Hello, did you copy `whitebg.png` file to the `%AppData%\Microsoft\AddIns`? If not, do that.

Also, which Excel version are you using?

**Comment by CajuEtex** [comment]
Yes, i copied the whitebg.png and the ExcelDarkThemeFix.xlam for C:\Users\[UserName]\AppData\Roaming\Microsoft\AddIns (is the same thing?).

I'm using the Microsoft Office Professional Plus 2019, the Excel version is 2009.

**Comment by matafokka** [comment]
Yes, it's the same thing, so there's nothing wrong with installation.
My Excel version is 2009 too. Well, then that error seems strange, I'll need some time to dig it in.

I have a couple of questions, because this information might be useful:

1. When you open Excel and create empty workbook, does the Add-In work, or the same error pops up?
1. If there's no error, can you provide any problematic workbook?
1. Which Windows build are you using? You can find it by running `winver` from search, CMD or by pressing `Win + R` and typing it.

P. S. Sorry about troubling you, it's just MS product being MS product :D

**Comment by matafokka** [comment]
Hmm, I played a bit with Excel and got the same error only when path in script points to the non-existing file.
So I suspect that your problem is related to the user accounts (if MS Office has been installed from another account) or something like that.
I changed a few things and made a message box with debug information.

So please, do the following:
1. Replace the original file `ExcelDarkThemeFix.xlam` with file from [this archive](https://github.com/matafokka/ExcelDarkThemeFix/files/5409680/ExcelDarkThemeFix.zip).
1. Open one of your workbooks.
1. The message box will pop up. Take a screenshot of it and post it here. If you don't want to show your account name, blank it and tell if it's the same in all three rows and if it's the name of the account you are currently logged in to.
1. Tell if your error is still present.

**Comment by CajuEtex** [comment]
> 1. When you open Excel and create empty workbook, does the Add-In work, or the same error pops up?
Yes, that's an empty workbook below
![image](https://user-images.githubusercontent.com/73147420/96616951-5e0c4e00-12d9-11eb-9c39-d45081e35025.png)
> 2. If there's no error, can you provide any problematic workbook?
> 3. Which Windows build are you using? You can find it by running `winver` from search, CMD or by pressing `Win + R` and typing it.
I'm using the version: 2004 / build: 19041.572
>

**Comment by CajuEtex** [comment]
> 1. Replace the original file `ExcelDarkThemeFix.xlam` with file from [this archive](https://github.com/matafokka/ExcelDarkThemeFix/files/5409680/ExcelDarkThemeFix.zip).
> 2. Open one of your workbooks.
> 3. The message box will pop up. Take a screenshot of it and post it here. If you don't want to show your account name, blank it and tell if it's the same in all three rows and if it's the name of the account you are currently logged in to.
![image](https://user-images.githubusercontent.com/73147420/96620353-b5142200-12dd-11eb-8435-713829ca2e4e.png)
I don't understand that part: (tell if it's the same in all three rows and if it's the name of the account you are currently logged in to.) 
Do you want to know if the account logged on the Office is the same as the Windows 10?
if yes, then is the same.
> 4. Tell if your error is still present.
![image](https://user-images.githubusercontent.com/73147420/96620516-eab90b00-12dd-11eb-8343-4cb1ab827a08.png)
Now i get this error hahaha, i'm almost giving up of this windows theme

**Comment by CajuEtex** [comment]
It seems that in some workbooks with one sheet it works, but if i try a workbook with many sheets a get this error 
![image](https://user-images.githubusercontent.com/73147420/96621375-ef31f380-12de-11eb-9ad8-41fa68562c7a.png)
just the first 3 sheets that changes the colors, but the rest of them don't, this is the third sheet:
![image](https://user-images.githubusercontent.com/73147420/96621592-2dc7ae00-12df-11eb-9bad-1e20b23cb2d0.png)
and this is the fourth onwards:
![image](https://user-images.githubusercontent.com/73147420/96621625-3c15ca00-12df-11eb-93fd-ab7eb9074d68.png)

**Comment by matafokka** [comment]
Whoa, that change worked! :D 
*If you're interested, the old method was pointing to the Downloads instead of AppData for some reason. New method explicitly points to the AppData, so we fixed the original error. The new error is completely unrelated to the previous one, gonna fix it now.*

I'm gonna create such a workbook, but, if it's possible, can you send yours in case if I won't be able to reproduce this error?

>     i'm almost giving up of this windows theme

No, don't give up! Theming is a beautiful thing and, despite all Microsoft intentions to destroy it, various devs keep it up. We're surely gonna deal with you errors, so you and everybody else will be able to use this Add-In. I've spent too much time on it to just give it up :D

**Comment by matafokka** [comment]
I did some testing and stumbled upon your new error. It is related to the shape types that almost no one uses and I've never heard of which. I hope I'll have time to do all the testing until tomorrow's evening. So stay tuned for the updates.

But I still want to check your workbook to ensure that everything is going fine.

**Comment by CajuEtex** [comment]
Here is my workbooks:

[Banco de Dados Original.xlsx](https://github.com/matafokka/ExcelDarkThemeFix/files/5411741/Banco.de.Dados.Original.xlsx)
[Banco de Dados Formatado - com Gráfico.xlsx](https://github.com/matafokka/ExcelDarkThemeFix/files/5411742/Banco.de.Dados.Formatado.-.com.Grafico.xlsx)
[Banco de Dados Formatado.xlsx](https://github.com/matafokka/ExcelDarkThemeFix/files/5411743/Banco.de.Dados.Formatado.xlsx)

Just ignore the foreign language hahaha

**Comment by CajuEtex** [comment]
Don't worry with the time is not that urgent 😄

**Comment by matafokka** [comment]
Thanks, I'll try to fix all of that as fast as I can, but I have very tight schedule, so no ETA :)

**Comment by matafokka** [comment]
Hello, I just updated the Add-In, now your problems are fixed. Please, download `ExcelDarkTheme.xlam` again and replace existing file. Thanks for reporting your issues!

**Comment by CajuEtex** [comment]
Thank you very much ❤️ , now it worked, but i had to put the ExcelDarkTheme.xlam file on the Excel > XLSTART paste to work, because the files only in the AddIns paste it didn't work.

**Comment by matafokka** [comment]
No, thank YOU for contributing and using my software :)

Can you explain what happened? Was there any error at startup when you've put `ExcelDarkTheme.xlam` in AppData? Should I update documentation?

**Comment by CajuEtex** [comment]
no errors appeared, but with the ExcelDarkTheme.xlam only in the AddIns folder nothing happend, the workbook remained the same with the dark colors, only when i put in the XLSTART folder that it worked. I left the ExcelDarkTheme.xlam in the two folders (AddIns and XLSTART) and the white.png only in the AddIns folder.

Like that:
![image](https://user-images.githubusercontent.com/73147420/96934992-95295d80-1499-11eb-8632-4ca4bcb7e1eb.png)
![image](https://user-images.githubusercontent.com/73147420/96935169-eafe0580-1499-11eb-80ea-44d2a86b319d.png)

**Comment by matafokka** [comment]
Hm...  When it was in AppData, did it show up in Developers - Excel Add-Is? Did you enable it there? I'm asking because XLSTART isn't a great place for such Add-Ins.

Warning: below goes my ranting :D

If there will be a critical bug or something, user won't be able to just disable an Add-In. They'll need to go to XLSTART and manually remove it.

Though, XLSTART seems an easier way to install Add-Ins. AFAIK, it doesn't require tweaking Trust Center.

Gotta think about it, I might update the docs or create an installer if I'll choose using XLSTART.

**Comment by CajuEtex** [comment]
> Hm... When it was in AppData, did it show up in Developers - Excel Add-Is? Yes
Did you enable it there? Yes
![image](https://user-images.githubusercontent.com/73147420/97011928-aae06680-151d-11eb-9d6a-d61afbd84542.png)

**Comment by matafokka** [comment]
Well, that's really weird, I don't know what can prevent script from working besides "Enable" checkbox and Trust Center settings.

Anyway, thank you, I'll test it with XLSTART and update documentation. Probably, XLSTART will be that good that there will be no need in any manual operations, so I'll be able to create an installer.

**Comment by matafokka** [comment]
Hello, I tested ExcelDarkThemeFix with XLSTART and it works fine so far. I added compatibility with XLSTART, so now you don't need to store everything in separate folders, and also fixed some important possible bugs.

Please, download an updated version and check ReadMe on how to install in XLSTART. It's way easier than installing to AppData :D

P. S. Thank you for telling me all of these, I wouldn't even know about these bugs without your help. It has been pleasure working with you! :)

**Comment by CajuEtex** [comment]
Now is working perfectly, I'm happy that i could help you in some way 😃 , maybe if is possible in the future you could make some for OneNote? 😄

**Comment by matafokka** [comment]
Unfortunately, I don't use OneNote and I don't know what to change. It was pain to do this for Excel, for OneNote it will be a disaster :D

Does it actually suffer from the same problems as Excel?

And if you need to share your stuff, better use Word. The latest versions use right colors by default and .docx or .odf are more suitable for sharing.

If you use OneNote just for notes, better switch to another application. IMO, MS crap is more like a need rather than helpful tools, so if you can avoid it, do so :D

**Comment by CajuEtex** [comment]
Does it actually suffer from the same problems as Excel? Yes

Yea i guess i'm gonna switch for Canva, but anyway thank you very much ❤️

**Comment by matafokka** [comment]
Your welcome and thank you too again :)
