### ISSUE TITLE
MS Access Support?

### ISSUE THREAD

**Issue by rackodo** [matafokka/ExcelDarkThemeFix#6]
I'm using Microsoft Access for school and it's hard to read the text I'm putting in with my theme. Any chance for an Access add-in?

**Comment by matafokka** [comment]
Hello, if its UI (such as cells' text color and background) can be customized, it should be possible to create such Add-In. Otherwise, we're out of luck.

Since I've got to look into couple of issues with the other more widely used MS Office programs and I have very little free time, I won't promise anything.

As an alternative, I suggest to try built-in dark theme or better, switch to another database client. I highly recommend DBeaver. Talk to your teacher, they will allow it if they're somewhat of a sane person.

Anyway, closing this issue as unrelated. I'm sorry.
