### ISSUE TITLE
Fix for Word 2021

### ISSUE THREAD

**Issue by StarNumber12046** [matafokka/ExcelDarkThemeFix#7]
I need a Word version of this because setting a white page makes the UI buggy and glitched

**Comment by matafokka** [comment]
Hello, Word version won't be there at least until new year, sorry. Got a lot of stuff to do in uni.

There shouldn't be any problem in Word, unless you're using files made in old Word versions or from LibreOffice. For the past few years, I haven't had any problems with relatively new files whatsoever. What I've made like 3-4 years ago opens just fine.

Can you send me one of your files (replace text with random letters, if it's private information, I just need formatting) and show me what exactly you're doing?

Also, try resetting Word template and styles, if you've updated from like Office 2007 or downloaded or made them yourself. This stuff might have automatic colors which causes the issue.

**Comment by StarNumber12046** [comment]
no if I set dark theme  I have a black page by default and if I change I have A LOT of bugs / glitches

**Comment by StarNumber12046** [comment]
with Word Beta 2021
![image](https://user-images.githubusercontent.com/64470722/135880956-78fc11e6-1fa7-4e72-91fd-8117d9fd365a.png)
the document

**Comment by StarNumber12046** [comment]
![image](https://user-images.githubusercontent.com/64470722/135881200-27d94b69-7273-448e-8d1f-16d0457727f6.png)
selection when changing color to black that renders white

**Comment by matafokka** [comment]
Well, that can be expected from beta, they'll probably fix it in the final version, so I'll wait until the release. For now, switch to Office 2019 or 2016.

If final release will be broken, I'll try to make an Add-In ASAP. Please, reopen this issue, if problem will persist.

**Comment by matafokka** [comment]
Hello again, just installed Office 2021, and it seems like what you've described is what looks like a feature:

1. Word makes page dark only when dark theme in Word is selected. Selecting White, Colorful or Dark Grey renders page white.
2. It does the same even when system theme is set to default white.
3. When printing, it prints page correctly. I assume, if it was a bug, it would print white text as we saw in Excel.

I have found only one issue so far - when setting white highlight and automatic text color, when custom theme is applied, text color renders really dark grey instead of white. But this issue is so insignificant and use cases are so rare, it's not worth a separate tweak.

Back to the fix.

Click **File - Account - Office Theme** and set any theme you like except Black.

![image](https://user-images.githubusercontent.com/34414488/136400628-1e635336-df9f-4b9c-af53-f463d330e72d.png)

This is how it works on my machine:

![image](https://user-images.githubusercontent.com/34414488/136401486-307569d9-7431-4bf6-8f7b-9520999ba275.png)

**Comment by StarNumber12046** [comment]
yes but i dont like the color dark grey

**Comment by matafokka** [comment]
Well, choose one you like the most or hate the least, there's no other option. As for the black theme, I'm not gonna fix what's already working.

**Comment by matafokka** [comment]
I am so dumb. There's official docs on this feature. It can be disabled.

https://insider.office.com/en-us/blog/try-dark-mode-in-word
